### ISSUE TITLE
这个没有太大的用处吧！没有vip账号的，只能爬你账号有权限的观看的视频

### ISSUE THREAD

**Issue by lipeng1a** [xiciliu/WanmenDownloader#1]
这个没有太大的用处吧！没有vip账号的，只能爬你账号有权限的观看的视频

**Comment by xiciliu** [comment]
对购买的课程有用吧。有时来不及看。就先下载下来。有人提供一个VIP账号就更好啦。

**Comment by caicaiacai** [comment]
> 对购买的课程有用吧。有时来不及看。就先下载下来。有人提供一个VIP账号就更好啦。

大佬，，想求一下脚本可以嘛？下载下来只有一个SpiderWanmen.py，，好像用不了，，，求个完整脚本，，，还是很有用的谢谢！！！                            sweetxin.mail@gmail.com
